DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
DROP TABLE IF EXISTS country_descriptions CASCADE;
DROP TABLE IF EXISTS media CASCADE;
DROP TABLE IF EXISTS dances CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
